// Package models contains the types for schema 'public'.
package models

// Code generated by xo. DO NOT EDIT.

// EpubsNumberOfPages represents a row from '[custom epubs_number_of_pages]'.
type EpubsNumberOfPages struct {
	Isbn          string // isbn
	NumberOfPages int64  // number_of_pages
}

// GetEpubsNumberOfPages runs a custom query, returning results as EpubsNumberOfPages.
func GetEpubsNumberOfPages(db XODB) ([]*EpubsNumberOfPages, error) {
	var err error

	// sql query
	const sqlstr = `SELECT LEFT(RIGHT(oee.source, 18), 13) AS isbn, COUNT(ol.*) as number_of_pages ` +
		`FROM otx_epub_epub oee INNER JOIN occurrence_location ol on oee.document_ptr_id = ol.document_id ` +
		`GROUP BY isbn ` +
		`ORDER BY isbn`

	// run query
	XOLog(sqlstr)
	q, err := db.Query(sqlstr)
	if err != nil {
		return nil, err
	}
	defer q.Close()

	// load results
	res := []*EpubsNumberOfPages{}
	for q.Next() {
		enop := EpubsNumberOfPages{}

		// scan
		err = q.Scan(&enop.Isbn, &enop.NumberOfPages)
		if err != nil {
			return nil, err
		}

		res = append(res, &enop)
	}

	return res, nil
}
