// Package models contains the types for schema 'public'.
package models

// Code generated by xo. DO NOT EDIT.

// ExternalRelationsForTopic represents a row from '[custom external_relations_for_topic]'.
type ExternalRelationsForTopic struct {
	Vocabulary   string // vocabulary
	URL          string // url
	Relationship string // relationship
}

// ExternalRelationsForTopicsByTopic_id runs a custom query, returning results as ExternalRelationsForTopic.
func ExternalRelationsForTopicsByTopic_id(db XODB, topic_id int) ([]*ExternalRelationsForTopic, error) {
	var err error

	// sql query
	const sqlstr = `SELECT ` +
		`SUBSTRING(oww.content FROM '^(.*) *\([^()]+\)$') AS vocabulary, ` +
		`oww.url, ` +
		`SUBSTRING(oww.content FROM '\(([^()]+)\)$') AS relationship ` +
		` ` +
		`FROM otx_weblink_weblink oww INNER JOIN otx_weblink_weblink_baskets owwb on oww.id = owwb.weblink_id ` +
		` ` +
		`WHERE owwb.basket_id = $1 ` +
		` ` +
		`ORDER BY vocabulary, url, relationship`

	// run query
	XOLog(sqlstr, topic_id)
	q, err := db.Query(sqlstr, topic_id)
	if err != nil {
		return nil, err
	}
	defer q.Close()

	// load results
	res := []*ExternalRelationsForTopic{}
	for q.Next() {
		erft := ExternalRelationsForTopic{}

		// scan
		err = q.Scan(&erft.Vocabulary, &erft.URL, &erft.Relationship)
		if err != nil {
			return nil, err
		}

		res = append(res, &erft)
	}

	return res, nil
}
