// Package models contains the types for schema 'public'.
package models

// Code generated by xo. DO NOT EDIT.

// TopicNumberOfOccurrences represents a row from '[custom topic_number_of_occurrences]'.
type TopicNumberOfOccurrences struct {
	BasketID            int   // basket_id
	NumberOfOccurrences int64 // number_of_occurrences
}

// TopicNumberOfOccurrencesByTopic_id runs a custom query, returning results as TopicNumberOfOccurrences.
func TopicNumberOfOccurrencesByTopic_id(db XODB, topic_id int) ([]*TopicNumberOfOccurrences, error) {
	var err error

	// sql query
	const sqlstr = `SELECT basket_id, COUNT(*) AS number_of_occurrences ` +
		`FROM occurrence_occurrence ` +
		`WHERE basket_id = $1 ` +
		`GROUP BY basket_id`

	// run query
	XOLog(sqlstr, topic_id)
	q, err := db.Query(sqlstr, topic_id)
	if err != nil {
		return nil, err
	}
	defer q.Close()

	// load results
	res := []*TopicNumberOfOccurrences{}
	for q.Next() {
		tnoo := TopicNumberOfOccurrences{}

		// scan
		err = q.Scan(&tnoo.BasketID, &tnoo.NumberOfOccurrences)
		if err != nil {
			return nil, err
		}

		res = append(res, &tnoo)
	}

	return res, nil
}
