// Package models contains the types for schema 'public'.
package models

// Code generated by xo. DO NOT EDIT.

// TopicAlternateNames represents a row from '[custom topic_alternate_names]'.
type TopicAlternateNames struct {
	ID          int    // id
	DisplayName string // display_name
	Name        string // name
}

// GetTopicAlternateNames runs a custom query, returning results as TopicAlternateNames.
func GetTopicAlternateNames(db XODB) ([]*TopicAlternateNames, error) {
	var err error

	// sql query
	const sqlstr = `SELECT hb.id, hb.display_name, hh.name FROM hit_basket hb INNER JOIN hit_hit hh ON hb.id = hh.basket_id ORDER BY display_name, name`

	// run query
	XOLog(sqlstr)
	q, err := db.Query(sqlstr)
	if err != nil {
		return nil, err
	}
	defer q.Close()

	// load results
	res := []*TopicAlternateNames{}
	for q.Next() {
		tan := TopicAlternateNames{}

		// scan
		err = q.Scan(&tan.ID, &tan.DisplayName, &tan.Name)
		if err != nil {
			return nil, err
		}

		res = append(res, &tan)
	}

	return res, nil
}
