// Copyright © 2017 NYU
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package main

import (
	"fmt"
	"os"

	"github.com/nyulibraries/dlts-enm/cmd"
)

//go:generate xo mysql://${ENM_DATABASE_USERNAME}:${ENM_DATABASE_PASSWORD}@localhost/${ENM_DATABASE} -o db/models/

// xo doesn't generate the desired go code for views, so we run in query mode to replace the *.go files generated by previous command.
// It was tricky getting these go:generate commands right.  Here is a list of previous attempts that did not seem to work:
//
// * Before I realized there was a --query param, was mimicking the xo README.md example by feeding the query into stdin:
//     * go:generate xo echo 'SELECT * FROM page' | go:generate xo mysql://${ENM_DATABASE_USERNAME}:${ENM_DATABASE_PASSWORD}@localhost/${ENM_DATABASE} --query-mode --query-trim --query-strip --query-type Page --out db/models/
//     * go:generate xo sh -c "echo 'SELECT * FROM page' | go:generate xo mysql://${ENM_DATABASE_USERNAME}:${ENM_DATABASE_PASSWORD}@localhost/${ENM_DATABASE} --query-mode --query-trim --query-strip --query-type Page --out db/models/"
//     * go:generate xo sh -c 'echo "SELECT * FROM page" | go:generate xo mysql://${ENM_DATABASE_USERNAME}:${ENM_DATABASE_PASSWORD}@localhost/${ENM_DATABASE} --query-mode --query-trim --query-strip --query-type Page --out db/models/'
// * After learning about --query param (note the single quotes used in --query param, only double-quotes seem to work):
//     * go:generate xo mysql://${ENM_DATABASE_USERNAME}:${ENM_DATABASE_PASSWORD}@localhost/${ENM_DATABASE} --query-mode --query-trim --query-strip --query 'SELECT * FROM pages' --query-type Page --out db/models/

//go:generate xo mysql://${ENM_DATABASE_USERNAME}:${ENM_DATABASE_PASSWORD}@localhost/${ENM_DATABASE} --query-mode --query-trim --query-strip --query "SELECT * FROM epubs_number_of_pages" --query-type EpubsNumberOfPage --out db/models/
//go:generate xo mysql://${ENM_DATABASE_USERNAME}:${ENM_DATABASE_PASSWORD}@localhost/${ENM_DATABASE} --query-mode --query-trim --query-strip --query "SELECT * FROM pages" --query-type Page --out db/models/
//go:generate xo mysql://${ENM_DATABASE_USERNAME}:${ENM_DATABASE_PASSWORD}@localhost/${ENM_DATABASE} --query-mode --query-trim --query-strip --query "SELECT * FROM page_topic_names" --query-type PageTopicName --out db/models/
//go:generate xo mysql://${ENM_DATABASE_USERNAME}:${ENM_DATABASE_PASSWORD}@localhost/${ENM_DATABASE} --query-mode --query-trim --query-strip --query "SELECT * FROM topics_with_sort_keys" --query-type TopicsWithSortKeys --out db/models/

//go:generate xo/scripts/generate-models-for-topic-page-queries.sh

func main() {
	if err := cmd.RootCmd.Execute(); err != nil {
		fmt.Println(err)
		os.Exit(-1)
	}
}