// Package models contains the types for schema 'enm'.
package models

// GENERATED BY XO. DO NOT EDIT.

import (
	"errors"
)

// EditorialReviewStatusStatus represents a row from 'enm.editorial_review_status_statuses'.
type EditorialReviewStatusStatus struct {
	ID     int    `json:"id"`     // id
	Status string `json:"status"` // status

	// xo fields
	_exists, _deleted bool
}

// Exists determines if the EditorialReviewStatusStatus exists in the database.
func (erss *EditorialReviewStatusStatus) Exists() bool {
	return erss._exists
}

// Deleted provides information if the EditorialReviewStatusStatus has been deleted from the database.
func (erss *EditorialReviewStatusStatus) Deleted() bool {
	return erss._deleted
}

// Insert inserts the EditorialReviewStatusStatus to the database.
func (erss *EditorialReviewStatusStatus) Insert(db XODB) error {
	var err error

	// if already exist, bail
	if erss._exists {
		return errors.New("insert failed: already exists")
	}

	// sql insert query, primary key must be provided
	const sqlstr = `INSERT INTO enm.editorial_review_status_statuses (` +
		`id, status` +
		`) VALUES (` +
		`?, ?` +
		`)`

	// run query
	XOLog(sqlstr, erss.ID, erss.Status)
	_, err = db.Exec(sqlstr, erss.ID, erss.Status)
	if err != nil {
		return err
	}

	// set existence
	erss._exists = true

	return nil
}

// Update updates the EditorialReviewStatusStatus in the database.
func (erss *EditorialReviewStatusStatus) Update(db XODB) error {
	var err error

	// if doesn't exist, bail
	if !erss._exists {
		return errors.New("update failed: does not exist")
	}

	// if deleted, bail
	if erss._deleted {
		return errors.New("update failed: marked for deletion")
	}

	// sql query
	const sqlstr = `UPDATE enm.editorial_review_status_statuses SET ` +
		`status = ?` +
		` WHERE id = ?`

	// run query
	XOLog(sqlstr, erss.Status, erss.ID)
	_, err = db.Exec(sqlstr, erss.Status, erss.ID)
	return err
}

// Save saves the EditorialReviewStatusStatus to the database.
func (erss *EditorialReviewStatusStatus) Save(db XODB) error {
	if erss.Exists() {
		return erss.Update(db)
	}

	return erss.Insert(db)
}

// Delete deletes the EditorialReviewStatusStatus from the database.
func (erss *EditorialReviewStatusStatus) Delete(db XODB) error {
	var err error

	// if doesn't exist, bail
	if !erss._exists {
		return nil
	}

	// if deleted, bail
	if erss._deleted {
		return nil
	}

	// sql query
	const sqlstr = `DELETE FROM enm.editorial_review_status_statuses WHERE id = ?`

	// run query
	XOLog(sqlstr, erss.ID)
	_, err = db.Exec(sqlstr, erss.ID)
	if err != nil {
		return err
	}

	// set deleted
	erss._deleted = true

	return nil
}

// EditorialReviewStatusStatusByID retrieves a row from 'enm.editorial_review_status_statuses' as a EditorialReviewStatusStatus.
//
// Generated from index 'editorial_review_status_statuses_id_pkey'.
func EditorialReviewStatusStatusByID(db XODB, id int) (*EditorialReviewStatusStatus, error) {
	var err error

	// sql query
	const sqlstr = `SELECT ` +
		`id, status ` +
		`FROM enm.editorial_review_status_statuses ` +
		`WHERE id = ?`

	// run query
	XOLog(sqlstr, id)
	erss := EditorialReviewStatusStatus{
		_exists: true,
	}

	err = db.QueryRow(sqlstr, id).Scan(&erss.ID, &erss.Status)
	if err != nil {
		return nil, err
	}

	return &erss, nil
}
