// Package models contains the types for schema 'enm'.
package models

// GENERATED BY XO. DO NOT EDIT.

// PageTopic represents a row from '[custom page_topic]'.
type PageTopic struct {
	PageID             int    // page_id
	TopicID            int    // topic_id
	PreferredTopicName string // preferred_topic_name
}

// GetPageTopics runs a custom query, returning results as PageTopic.
func GetPageTopics(db XODB) ([]*PageTopic, error) {
	var err error

	// sql query
	const sqlstr = `SELECT * FROM page_topics`

	// run query
	XOLog(sqlstr)
	q, err := db.Query(sqlstr)
	if err != nil {
		return nil, err
	}
	defer q.Close()

	// load results
	res := []*PageTopic{}
	for q.Next() {
		pt := PageTopic{}

		// scan
		err = q.Scan(&pt.PageID, &pt.TopicID, &pt.PreferredTopicName)
		if err != nil {
			return nil, err
		}

		res = append(res, &pt)
	}

	return res, nil
}
