// Package models contains the types for schema 'enm'.
package models

// GENERATED BY XO. DO NOT EDIT.

import (
	"database/sql"
)

// PageTopic represents a row from 'enm.page_topics'.
type PageTopic struct {
	PageID             int            `json:"page_id"`              // page_id
	TopicID            sql.NullInt64  `json:"topic_id"`             // topic_id
	PreferredTopicName sql.NullString `json:"preferred_topic_name"` // preferred_topic_name
}
