// Package models contains the types for schema 'enm'.
package models

// GENERATED BY XO. DO NOT EDIT.

// PageTopicName represents a row from '[custom page_topic_name]'.
type PageTopicName struct {
	PageID             int    // page_id
	TopicID            int    // topic_id
	PreferredTopicName string // preferred_topic_name
	TopicName          string // topic_name
}

// GetPageTopicNames runs a custom query, returning results as PageTopicName.
func GetPageTopicNames(db XODB) ([]*PageTopicName, error) {
	var err error

	// sql query
	const sqlstr = `SELECT * FROM page_topic_names`

	// run query
	XOLog(sqlstr)
	q, err := db.Query(sqlstr)
	if err != nil {
		return nil, err
	}
	defer q.Close()

	// load results
	res := []*PageTopicName{}
	for q.Next() {
		ptn := PageTopicName{}

		// scan
		err = q.Scan(&ptn.PageID, &ptn.TopicID, &ptn.PreferredTopicName, &ptn.TopicName)
		if err != nil {
			return nil, err
		}

		res = append(res, &ptn)
	}

	return res, nil
}
