// Package models contains the types for schema 'enm'.
package models

// GENERATED BY XO. DO NOT EDIT.

import (
	"database/sql"
)

// Page represents a row from 'enm.pages'.
type Page struct {
	ID           int            `json:"id"`            // id
	Title        sql.NullString `json:"title"`         // title
	Authors      sql.NullString `json:"authors"`       // authors
	Publisher    sql.NullString `json:"publisher"`     // publisher
	Isbn         sql.NullString `json:"isbn"`          // isbn
	PagePattern  sql.NullString `json:"page_pattern"`  // page_pattern
	PageLocalid  string         `json:"page_localid"`  // page_localid
	PageSequence int            `json:"page_sequence"` // page_sequence
}
