// Package models contains the types for schema 'enm'.
package models

// GENERATED BY XO. DO NOT EDIT.

// ReadiumGotoURL represents a row from 'enm.readium_goto_urls'.
type ReadiumGotoURL struct {
	LocationID              int    `json:"location_id"`                // location_id
	ReadiumGotoValue        string `json:"readium_goto_value"`         // readium_goto_value
	ReadiumGotoURL          string `json:"readium_goto_url"`           // readium_goto_url
	ReadiumGotoValueEncoded string `json:"readium_goto_value_encoded"` // readium_goto_value_encoded
	ReadiumGotoURLEncoded   string `json:"readium_goto_url_encoded"`   // readium_goto_url_encoded
}
