// Package models contains the types for schema 'enm'.
package models

// GENERATED BY XO. DO NOT EDIT.

// TopicAlternateName represents a row from '[custom topic_alternate_name]'.
type TopicAlternateName struct {
	TctID               int    // tct_id
	DisplayNameDoNotUse string // display_name_do_not_use
	Name                string // name
}

// GetTopicAlternateNames runs a custom query, returning results as TopicAlternateName.
func GetTopicAlternateNames(db XODB) ([]*TopicAlternateName, error) {
	var err error

	// sql query
	const sqlstr = `SELECT t.tct_id, t.display_name_do_not_use, n.name ` +
		` ` +
		`FROM topics t INNER JOIN names n ON t.tct_id = n.topic_id ` +
		` ` +
		`ORDER BY t.display_name_do_not_use, n.name`

	// run query
	XOLog(sqlstr)
	q, err := db.Query(sqlstr)
	if err != nil {
		return nil, err
	}
	defer q.Close()

	// load results
	res := []*TopicAlternateName{}
	for q.Next() {
		tan := TopicAlternateName{}

		// scan
		err = q.Scan(&tan.TctID, &tan.DisplayNameDoNotUse, &tan.Name)
		if err != nil {
			return nil, err
		}

		res = append(res, &tan)
	}

	return res, nil
}
