// Package models contains the types for schema 'enm'.
package models

// GENERATED BY XO. DO NOT EDIT.

// TopicRelationsSimple represents a row from 'enm.topic_relations_simple'.
type TopicRelationsSimple struct {
	Topic1ID int `json:"topic1_id"` // topic1_id
	Topic2ID int `json:"topic2_id"` // topic2_id
}
