// Package models contains the types for schema 'enm'.
package models

// GENERATED BY XO. DO NOT EDIT.

// EpubsNumberOfPage represents a row from '[custom epubs_number_of_page]'.
type EpubsNumberOfPage struct {
	Isbn          string // ISBN
	NumberOfPages int64  // number_of_pages
}

// GetEpubsNumberOfPages runs a custom query, returning results as EpubsNumberOfPage.
func GetEpubsNumberOfPages(db XODB) ([]*EpubsNumberOfPage, error) {
	var err error

	// sql query
	const sqlstr = `SELECT * FROM epubs_number_of_pages`

	// run query
	XOLog(sqlstr)
	q, err := db.Query(sqlstr)
	if err != nil {
		return nil, err
	}
	defer q.Close()

	// load results
	res := []*EpubsNumberOfPage{}
	for q.Next() {
		enop := EpubsNumberOfPage{}

		// scan
		err = q.Scan(&enop.Isbn, &enop.NumberOfPages)
		if err != nil {
			return nil, err
		}

		res = append(res, &enop)
	}

	return res, nil
}
