// Package models contains the types for schema 'enm'.
package models

// GENERATED BY XO. DO NOT EDIT.

// PageTopicName represents a row from '[custom page_topic_name]'.
type PageTopicName struct {
	PageID                  int    // page_id
	TopicID                 int    // topic_id
	TopicDisplayName        string // topic_display_name
	TopicName               string // topic_name
	TopicDisplayNameSortKey string // topic_display_name_sort_key
	TopicNameSortKey        string // topic_name_sort_key
}

// GetPageTopicNames runs a custom query, returning results as PageTopicName.
func GetPageTopicNames(db XODB) ([]*PageTopicName, error) {
	var err error

	// sql query
	const sqlstr = `SELECT * FROM page_topic_names`

	// run query
	XOLog(sqlstr)
	q, err := db.Query(sqlstr)
	if err != nil {
		return nil, err
	}
	defer q.Close()

	// load results
	res := []*PageTopicName{}
	for q.Next() {
		ptn := PageTopicName{}

		// scan
		err = q.Scan(&ptn.PageID, &ptn.TopicID, &ptn.TopicDisplayName, &ptn.TopicName, &ptn.TopicDisplayNameSortKey, &ptn.TopicNameSortKey)
		if err != nil {
			return nil, err
		}

		res = append(res, &ptn)
	}

	return res, nil
}
