// Package models contains the types for schema 'enm'.
package models

// GENERATED BY XO. DO NOT EDIT.

// Page represents a row from '[custom page]'.
type Page struct {
	ID           int    // id
	Title        string // title
	Authors      string // authors
	Publisher    string // publisher
	Isbn         string // isbn
	PagePattern  string // page_pattern
	PageLocalid  string // page_localid
	PageSequence int    // page_sequence
	PageText     string // page_text
}

// GetPages runs a custom query, returning results as Page.
func GetPages(db XODB) ([]*Page, error) {
	var err error

	// sql query
	const sqlstr = `SELECT * FROM pages`

	// run query
	XOLog(sqlstr)
	q, err := db.Query(sqlstr)
	if err != nil {
		return nil, err
	}
	defer q.Close()

	// load results
	res := []*Page{}
	for q.Next() {
		p := Page{}

		// scan
		err = q.Scan(&p.ID, &p.Title, &p.Authors, &p.Publisher, &p.Isbn, &p.PagePattern, &p.PageLocalid, &p.PageSequence, &p.PageText)
		if err != nil {
			return nil, err
		}

		res = append(res, &p)
	}

	return res, nil
}
