// Package models contains the types for schema 'enm'.
package models

// GENERATED BY XO. DO NOT EDIT.

// TopicsWithSortKeys represents a row from '[custom topics_with_sort_keys]'.
type TopicsWithSortKeys struct {
	TctID                         int    // tct_id
	DisplayNameDoNotUse           string // display_name_do_not_use
	EditorialReviewStatusReviewer string // editorial_review_status_reviewer
	EditorialReviewStatusTime     string // editorial_review_status_time
	EditorialReviewStatusStateID  int    // editorial_review_status_state_id
	DisplayNameDoNotUseSortKey    string // display_name_do_not_use_sort_key
}

// GetTopicsWithSortKeys runs a custom query, returning results as TopicsWithSortKeys.
func GetTopicsWithSortKeys(db XODB) ([]*TopicsWithSortKeys, error) {
	var err error

	// sql query
	const sqlstr = `SELECT * FROM topics_with_sort_keys`

	// run query
	XOLog(sqlstr)
	q, err := db.Query(sqlstr)
	if err != nil {
		return nil, err
	}
	defer q.Close()

	// load results
	res := []*TopicsWithSortKeys{}
	for q.Next() {
		twsk := TopicsWithSortKeys{}

		// scan
		err = q.Scan(&twsk.TctID, &twsk.DisplayNameDoNotUse, &twsk.EditorialReviewStatusReviewer, &twsk.EditorialReviewStatusTime, &twsk.EditorialReviewStatusStateID, &twsk.DisplayNameDoNotUseSortKey)
		if err != nil {
			return nil, err
		}

		res = append(res, &twsk)
	}

	return res, nil
}
