// Package models contains the types for schema 'enm'.
package models

// GENERATED BY XO. DO NOT EDIT.

// TopicNumberOfOccurrences represents a row from '[custom topic_number_of_occurrences]'.
type TopicNumberOfOccurrences struct {
	TopicID             int   // topic_id
	NumberOfOccurrences int64 // number_of_occurrences
}

// TopicNumberOfOccurrencesByTopic_id runs a custom query, returning results as TopicNumberOfOccurrences.
func TopicNumberOfOccurrencesByTopic_id(db XODB, topic_id int) ([]*TopicNumberOfOccurrences, error) {
	var err error

	// sql query
	const sqlstr = `SELECT topic_id, COUNT(*) AS number_of_occurrences ` +
		`FROM occurrences ` +
		`WHERE topic_id = ? ` +
		`GROUP BY topic_id`

	// run query
	XOLog(sqlstr, topic_id)
	q, err := db.Query(sqlstr, topic_id)
	if err != nil {
		return nil, err
	}
	defer q.Close()

	// load results
	res := []*TopicNumberOfOccurrences{}
	for q.Next() {
		tnoo := TopicNumberOfOccurrences{}

		// scan
		err = q.Scan(&tnoo.TopicID, &tnoo.NumberOfOccurrences)
		if err != nil {
			return nil, err
		}

		res = append(res, &tnoo)
	}

	return res, nil
}
